/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum CaptureBackend {
  ScreenCaptureKit = 'ScreenCaptureKit',
  XCap = 'XCap'
}
export interface ScreenCaptureConfig {
  backend?: CaptureBackend
  fps?: number
}
export declare class ScreenCapture {
  constructor(callback: (...args: any[]) => any, config?: ScreenCaptureConfig | undefined | null)
  start(): Promise<void>
  stop(): void
}
