/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ScreenCapture {
  constructor(
    callbackOrConfig?: ((frame: FrameData) => void) | ScreenCaptureConfig,
    config?: ScreenCaptureConfig | null,
  )
  start(): Promise<void>
  stop(): void
  screenshot(): Promise<FrameData>
}

export declare const enum CaptureBackend {
  ScreenCaptureKit = 'ScreenCaptureKit',
  XCap = 'XCap',
}

export interface FrameData {
  width: number
  height: number
  stride: number
  rgba: Buffer
}

export interface ScreenCaptureConfig {
  backend?: CaptureBackend
  fps?: number
}
